name: bikeindex-scraper

dependencies:
  - python=3.7
  - pip
  - pip:
    - pandas
    - requests
    - tensorflow
    # dev
    - black
    - dvc
    - dvc[gs]
    - flake8
    - jupyter
    - rope
